/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/connect-wallet': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Connect Wallet
     * @description 登录
     */
    post: operations['connect_wallet_connect_wallet_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/open-financing': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Open Financing
     * @description 开启理财
     */
    post: operations['open_financing_open_financing_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/close-financing': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Close Financing
     * @description 关闭理财
     */
    post: operations['close_financing_close_financing_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/create-will': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create Will
     * @description 创建遗产
     */
    post: operations['create_will_create_will_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/set-will-release-time': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Set Will Release Time
     * @description 设置遗产执行时间
     */
    post: operations['set_will_release_time_set_will_release_time_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/set-will-beneficiary': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Set Will Beneficiary
     * @description 设置遗产受益人及比例
     */
    post: operations['set_will_beneficiary_set_will_beneficiary_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/set-will-insurance': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Set Will Insurance
     * @description 设置遗产投保状态
     */
    post: operations['set_will_insurance_set_will_insurance_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/set-will-finance': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Set Will Finance
     * @description 设置遗产理财状态
     */
    post: operations['set_will_finance_set_will_finance_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/deposit-will': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Deposit Will
     * @description 增加遗产
     */
    post: operations['deposit_will_deposit_will_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/withdraw-will': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Withdraw Will
     * @description 提取遗产
     */
    post: operations['withdraw_will_withdraw_will_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/withdraw-will-all': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Withdraw Will All
     * @description 提取全部遗产
     */
    post: operations['withdraw_will_all_withdraw_will_all_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/create-social-security': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create Social Security
     * @description 创建社保
     */
    post: operations['create_social_security_create_social_security_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/set-social-security-insurance': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Set Social Security Insurance
     * @description 设置社保投保状态
     */
    post: operations['set_social_security_insurance_set_social_security_insurance_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/set-social-security-finance': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Set Social Security Finance
     * @description 设置社保理财状态
     */
    post: operations['set_social_security_finance_set_social_security_finance_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/deposit-social-security': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Deposit Social Security
     * @description 增加社保
     */
    post: operations['deposit_social_security_deposit_social_security_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/create-trust': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create Trust
     * @description 创建信托
     */
    post: operations['create_trust_create_trust_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/set-trust-release-time': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Set Trust Release Time
     * @description 设置信托下一次领取时间
     */
    post: operations['set_trust_release_time_set_trust_release_time_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/set-trust-beneficiary': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Set Trust Beneficiary
     * @description 设置信托受益人及比例
     */
    post: operations['set_trust_beneficiary_set_trust_beneficiary_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/set-trust-release-percent': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Set Trust Release Percent
     * @description 设置信托每个月可领取比例
     */
    post: operations['set_trust_release_percent_set_trust_release_percent_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/set-trust-insurance': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Set Trust Insurance
     * @description 设置信托投保状态
     */
    post: operations['set_trust_insurance_set_trust_insurance_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/set-trust-finance': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Set Trust Finance
     * @description 设置信托理财状态
     */
    post: operations['set_trust_finance_set_trust_finance_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/deposit-trust': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Deposit Trust
     * @description 增加信托
     */
    post: operations['deposit_trust_deposit_trust_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/withdraw-trust': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Withdraw Trust
     * @description 提取信托
     */
    post: operations['withdraw_trust_withdraw_trust_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/withdraw-trust-all': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Withdraw Trust All
     * @description 提取全部信托
     */
    post: operations['withdraw_trust_all_withdraw_trust_all_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/get-will': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Will
     * @description 获取遗产信息
     */
    get: operations['get_will_get_will_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/get-social-security': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Social Security
     * @description 获取社保信息
     */
    get: operations['get_social_security_get_social_security_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/get-trust': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Trust
     * @description 获取信托信息
     */
    get: operations['get_trust_get_trust_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/get-balance': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Balance
     * @description 获取用户余额
     */
    get: operations['get_balance_get_balance_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/get-fee-rates': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Fee Rates
     * @description 获取各种费率信息
     */
    get: operations['get_fee_rates_get_fee_rates_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/get-asset-operations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Asset Operations
     * @description 获取用户在某一资产模式下的全部操作记录
     */
    get: operations['get_asset_operations_get_asset_operations_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Status
     * @description 健康检查
     */
    get: operations['status_status_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * AssetMode
     * @enum {integer}
     */
    AssetMode: 0 | 1 | 2
    /** AssetOperation */
    AssetOperation: {
      /** Timestamp */
      timestamp: number
      /** Operation Type */
      operation_type: string
      /** Token */
      token: string
      /** Amount */
      amount: number
    }
    /** Beneficiary */
    Beneficiary: {
      /** Benaddr */
      benAddr: string
      /** Percent */
      percent: number
    }
    /** CalldataResponse */
    CalldataResponse: {
      /** Code */
      code: number
      /** Calldata */
      calldata: string
    }
    /** ConnectWalletRequest */
    ConnectWalletRequest: {
      /** Address */
      address: string
      /** Signature */
      signature: string
      /** Message */
      message: string
    }
    /** ConnectWalletResponse */
    ConnectWalletResponse: {
      /** Code */
      code: number
      /** Message To Sign */
      message_to_sign: string | null
      /** Authorization */
      authorization: string | null
    }
    /** CreateSocialSecurityRequest */
    CreateSocialSecurityRequest: {
      /** Release Time */
      release_time: number
      /** Is Insured */
      is_insured: boolean
      /** Release Months */
      release_months: number
    }
    /** CreateTrustRequest */
    CreateTrustRequest: {
      /** Release Time */
      release_time: number
      /** Is Insured */
      is_insured: boolean
      /** Beneficiaries */
      beneficiaries: components['schemas']['Beneficiary'][]
      /** Release Percent */
      release_percent: number
    }
    /** CreateWillRequest */
    CreateWillRequest: {
      /** Release Time */
      release_time: number
      /** Is Insured */
      is_insured: boolean
      /** Beneficiaries */
      beneficiaries: components['schemas']['Beneficiary'][]
    }
    /** FinancingRequest */
    FinancingRequest: {
      /** Message */
      message: string
      /** Messagesignature */
      messageSignature: string
    }
    /** FinancingResponse */
    FinancingResponse: {
      /** Code */
      code: number
    }
    /** GetAssetOperationsResponse */
    GetAssetOperationsResponse: {
      /** Code */
      code: number
      /** Total */
      total: number
      /** Operations */
      operations: components['schemas']['AssetOperation'][]
    }
    /** GetBalanceResponse */
    GetBalanceResponse: {
      /** Code */
      code: number
      /** Balance */
      balance: number
    }
    /** GetFeeRatesResponse */
    GetFeeRatesResponse: {
      /** Code */
      code: number
      /** Feeratewill */
      feeRateWill: number
      /** Feeratesocialsecurity */
      feeRateSocialSecurity: number
      /** Feeratetrust */
      feeRateTrust: number
      /** Insurancerate */
      insuranceRate: number
    }
    /** GetSocialSecurityResponse */
    GetSocialSecurityResponse: {
      /** Code */
      code: number
      /** Releasetime */
      ReleaseTime: number
      /** Isinsured */
      isInsured: boolean
      /** Lastpremiumtime */
      lastPremiumTime: number
      /** Assets */
      assets: components['schemas']['TokenAmount'][]
      /** Totalvalueusd */
      totalValueUSD: number | null
      /** Releasemonths */
      releaseMonths: number
    }
    /** GetTrustResponse */
    GetTrustResponse: {
      /** Code */
      code: number
      /** Releasetime */
      ReleaseTime: number
      /** Isinsured */
      isInsured: boolean
      /** Lastpremiumtime */
      lastPremiumTime: number
      /** Assets */
      assets: components['schemas']['TokenAmount'][]
      /** Totalvalueusd */
      totalValueUSD: number | null
      /** Beneficiaries */
      beneficiaries: components['schemas']['Beneficiary'][]
      /** Releasepercent */
      releasePercent: number
    }
    /** GetWillResponse */
    GetWillResponse: {
      /** Code */
      code: number
      /** Releasetime */
      releaseTime: number
      /** Isinsured */
      isInsured: boolean
      /** Lastpremiumtime */
      lastPremiumTime: number
      /** Assets */
      assets: components['schemas']['TokenAmount'][]
      /** Totalvalueusd */
      totalValueUSD: number | null
      /** Beneficiaries */
      beneficiaries: components['schemas']['Beneficiary'][]
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** MultiCalldataResponse */
    MultiCalldataResponse: {
      /** Code */
      code: number
      /** Multicalldata */
      multiCalldata: components['schemas']['TypeCalldata'][]
    }
    /** SetBeneficiaryRequest */
    SetBeneficiaryRequest: {
      /** Beneficiaries */
      beneficiaries: components['schemas']['Beneficiary'][]
    }
    /** SetFinanceRequest */
    SetFinanceRequest: {
      /** Is Financed */
      is_financed: boolean
    }
    /** SetInsuranceRequest */
    SetInsuranceRequest: {
      /** Is Insured */
      is_insured: boolean
    }
    /** SetReleaseTimeRequest */
    SetReleaseTimeRequest: {
      /** Release Time */
      release_time: number
    }
    /** SetTrustReleasePercentRequest */
    SetTrustReleasePercentRequest: {
      /** Release Percent */
      release_percent: number
    }
    /** TokenAmount */
    TokenAmount: {
      /** Token */
      token: string
      /** Amount */
      amount: number
    }
    /** TypeCalldata */
    TypeCalldata: {
      /** Type */
      type: string
      /** Calldata */
      calldata: string
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  connect_wallet_connect_wallet_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ConnectWalletRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ConnectWalletResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  open_financing_open_financing_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['FinancingRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FinancingResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  close_financing_close_financing_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['FinancingRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FinancingResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_will_create_will_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateWillRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CalldataResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  set_will_release_time_set_will_release_time_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SetReleaseTimeRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CalldataResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  set_will_beneficiary_set_will_beneficiary_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SetBeneficiaryRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CalldataResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  set_will_insurance_set_will_insurance_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SetInsuranceRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CalldataResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  set_will_finance_set_will_finance_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SetFinanceRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CalldataResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  deposit_will_deposit_will_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TokenAmount']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MultiCalldataResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  withdraw_will_withdraw_will_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TokenAmount']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CalldataResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  withdraw_will_all_withdraw_will_all_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CalldataResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_social_security_create_social_security_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateSocialSecurityRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CalldataResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  set_social_security_insurance_set_social_security_insurance_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SetInsuranceRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CalldataResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  set_social_security_finance_set_social_security_finance_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SetFinanceRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CalldataResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  deposit_social_security_deposit_social_security_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TokenAmount']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MultiCalldataResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_trust_create_trust_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateTrustRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CalldataResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  set_trust_release_time_set_trust_release_time_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SetReleaseTimeRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CalldataResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  set_trust_beneficiary_set_trust_beneficiary_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SetBeneficiaryRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CalldataResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  set_trust_release_percent_set_trust_release_percent_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SetTrustReleasePercentRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CalldataResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  set_trust_insurance_set_trust_insurance_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SetInsuranceRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CalldataResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  set_trust_finance_set_trust_finance_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SetFinanceRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CalldataResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  deposit_trust_deposit_trust_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TokenAmount']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MultiCalldataResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  withdraw_trust_withdraw_trust_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TokenAmount']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CalldataResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  withdraw_trust_all_withdraw_trust_all_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CalldataResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_will_get_will_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GetWillResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_social_security_get_social_security_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GetSocialSecurityResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_trust_get_trust_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GetTrustResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_balance_get_balance_get: {
    parameters: {
      query: {
        token: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GetBalanceResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_fee_rates_get_fee_rates_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GetFeeRatesResponse']
        }
      }
    }
  }
  get_asset_operations_get_asset_operations_get: {
    parameters: {
      query: {
        asset_mode: components['schemas']['AssetMode']
        limit?: number | null
        offset?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GetAssetOperationsResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  status_status_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
}
